package com.test.system.enums.groups;

public enum GroupError {
    INVITEE_NOT_FOUND,
    NOT_A_MEMBER,
    OWNER_ONLY,
    LIMIT_REACHED,
    TOKEN_REQUIRED,
    BAD_TOKEN_FORMAT,
    EMAIL_MISMATCH,
    MEMBERSHIP_NOT_FOUND,
    TARGET_NOT_IN_GROUP,
    TARGET_NOT_ACTIVE,
    CANNOT_REMOVE_OWNER,
    NAME_REQUIRED,
    NAME_TOO_SHORT,
    CANNOT_DELETE_PERSONAL,
    OWNER_CANNOT_LEAVE,
    USER_NOT_FOUND,
    GROUP_NOT_FOUND,
    MEMBERSHIP_NOT_ACTIVE,
    TARGET_IS_OWNER_ALREADY,
    USE_INVITE_CANCEL_ENDPOINT,
    MEMBER_NOT_ACTIVE,
    CANNOT_PROMOTE_TO_OWNER,
    MEMBERSHIP_GROUP_MISMATCH,
    NO_AUTH,
    OWNER_ROLE_FIXED
}

